# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
    - repo: https://github.com/ambv/black
      rev: 21.7b0
      hooks:
          - id: black
    - repo: https://github.com/pycqa/isort
      rev: "5.8.0"
      hooks:
          - id: isort
    - repo: https://github.com/pycqa/flake8
      rev: "3.9.2"
      hooks:
          - id: flake8
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: "v0.910"
      hooks:
          - id: mypy
            additional_dependencies:
                - "types-docutils>=0.17.0"
